title: Hossted!
name: Your Name
email: your-email@example.com
description: Hossted description
display_footer: inital  #change this to 'none' if you want to hide the footer copyright text

theme: jekyll-theme-slate
